"""Initial migration - User and Contact tables

Revision ID: 09dfe75fac5e
Revises: 
Create Date: 2026-07-12 04:08:36.558350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09dfe75fac5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Manually added: Alembic's autogenerate can't detect expression-based
    # indexes on SQLite, so this has to be written by hand. This is the
    # case-insensitive per-user duplicate-email constraint from the
    # Contact model - without it, the table has no protection against
    # duplicates at the database level.
    op.execute(
        "CREATE UNIQUE INDEX uq_contacts_user_email_ci "
        "ON contacts (user_id, lower(email))"
    )


def downgrade():
    op.execute("DROP INDEX IF EXISTS uq_contacts_user_email_ci")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
