"""Add undo_data column to activity_logs

Revision ID: 528eb6281b36
Revises: 36d3e879532f
Create Date: 2026-07-13 07:07:00.815068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528eb6281b36'
down_revision = '36d3e879532f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('undo_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_column('undo_data')

    # ### end Alembic commands ###
